export const StudentFormConfig = {
  initialValues: {
    registrationDate: "",
    firstName: "",
    middleName: "",
    lastName: "",
    dateOfBirth: "",
    age: "",
    sex: "",
    nationality: "",
    hometown: "",
    parentGuardian: "",
    address: "",
    occupation: "",
    religiousDenomination: "",
    houseNumber: "",
    phoneNumber: "",
    status: "",
  },
  fields: [
    { name: "registrationDate", label: "Registration Date", type: "date" },
    { name: "firstName", label: "First Name", type: "text" },
    { name: "middleName", label: "Middle Name", type: "text" },
    { name: "lastName", label: "Last Name", type: "text" },
    { name: "dateOfBirth", label: "Date of Birth", type: "date" },
    { name: "age", label: "Age", type: "text" },
    { name: "sex", label: "Sex", type: "select", options: ["male", "female"] },
    { name: "nationality", label: "Nationality", type: "text" },
    { name: "hometown", label: "Hometown", type: "text" },
    { name: "parentGuardian", label: "Parent/Guardian", type: "text" },
    { name: "address", label: "Address", type: "text" },
    { name: "occupation", label: "Occupation", type: "text" },
    {
      name: "religiousDenomination",
      label: "Religious Denomination",
      type: "text",
    },
    { name: "houseNumber", label: "House Number", type: "text" },
    { name: "phoneNumber", label: "Phone Number", type: "text" },
  ],
};
