const schema = () => {
  return (
    <div>
      <h1>Basic9Recordform</h1>
      customID: dropdown,
      studentName: text,
      term: dropdown,
      mathematics_classScore:number,
      mathematics_examScore: number,
      mathematics_totalScore: number,
      mathematics_position: number,
      mathematics_grade: number,
      mathematics_remarks: text,
      english_classScore:number,
      english_examScore: number,
      english_totalScore: number,
      english_position: number,
      english_grade: number,
      english_remarks: text,
      socialStudies_classScore:number,
      socialStudies_examScore: number,
      socialStudies_totalScore: number,
      socialStudies_position: number,
      socialStudies_grade: number,
      socialStudies_remarks: text,
      science_classScore:number,
      science_examScore: number,
      science_totalScore: number,
      science_position: number,
      science_grade: number,
      science_remarks: text,
      computing_classScore:number,
      computing_examScore: number,
      computing_totalScore: number,
      computing_position: number,
      computing_grade: number,
      computing_remarks: text,
      creativeArts_classScore:number,
      creativeArts_examScore: number,
      creativeArts_totalScore: number,
      creativeArts_position: number,
      creativeArts_grade: number,
      creativeArts_remarks: text,
      religiousAndMoralEducation_classScore:number,
      religiousAndMoralEducation_examScore: number,
      religiousAndMoralEducation_totalScore: number,
      religiousAndMoralEducation_position: number,
      religiousAndMoralEducation_grade: number,
      religiousAndMoralEducation_remarks: text,
      careerTechnology_classScore:number,
      careerTechnology_examScore: number,
      careerTechnology_totalScore: number,
      careerTechnology_position: number,
      careerTechnology_grade: number,
      careerTechnology_remarks: text,
      french_classScore:number,
      french_examScore: number,
      french_totalScore: number,
      french_position: number,
      french_grade: number,
      french_remarks: text,
      GhanaianLanguage_classScore:number,
      GhanaianLanguage_examScore: number,
      GhanaianLanguage_totalScore: number,
      GhanaianLanguage_position: number,
      GhanaianLanguage_grade: number,
      GhanaianLanguage_remarks: text,

      <h1>AddTeacherForm</h1>
      customID: dropdown,
      fullName: text,
      dateOfBirth: text,
      gender: dropdown,
      nationality:text,
      phone: number,
      email: email,
      address: text,
      qualifications: text,
      experience:text,
      position:text,
      startDate:date,
      salary: text,
      emergencyContact: number,
      status: dropdown,

      <h1>AddEventForm</h1>
      customID: dropdown,
      title:text,
      description: text,
      start:date,
      end: date,
      term: dropdown,
      status: dropdown,

      <h1>AddStudentForm</h1>
      customID: dropdown,
      registrationDate: date,
      firstName:text,
      middleName:text,
      lastName: text,
      dateOfBirth: date,
      age: number,
      sex: dropdown,
      nationality: text,
      hometown: text,
      parentGuardian: text,
      address: text,
      occupation: text,
      religiousDenomination: text,
      houseNumber: text,
      phoneNumber: number,
      status: dropdown,

      <h1>Register</h1>
      email: email,
      username:text,
      password: password

      <h1>Login</h1>
      email:emil,
      username:text
    </div>
  );
};

export default schema;
